###########################
# Configuration for rubocop
# in .rubocop.yml 
# Most of these are disabling existing cops, primarily
# due to a smattering of different styles and loose
# guidlines for contributions.
#
# Any of these may be changed.

AllCops:
  Exclude:
    - "spec/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "app/misc/**/*"
    - "config/**/*"
    - "bin/**/*"
    - "vendor/bundle/**/*"
    - "lib/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false